"""Add breeding events and sire_id dam_id

Revision ID: 4fffaddfdab0
Revises: 68787272dd92
Create Date: 2026-07-05 16:07:35.099558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app



# revision identifiers, used by Alembic.
revision: str = '4fffaddfdab0'
down_revision: Union[str, Sequence[str], None] = '68787272dd92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('base_salary', sa.Float(), nullable=False),
    sa.Column('performance_rating', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=False)
    op.create_table('staff_queries',
    sa.Column('staff_id', app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deduction_amount', sa.Float(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_queries_id'), 'staff_queries', ['id'], unique=False)
    op.add_column('breeding_events', sa.Column('sire_id', sa.String(length=50), nullable=True))
    op.add_column('breeding_events', sa.Column('semen_batch_id', sa.String(length=100), nullable=True))
    op.add_column('breeding_events', sa.Column('technician', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('OWNER', 'VET', 'MANAGER', 'WORKER', 'PHARMACIST', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.alter_column('transactions', 'reversal_of',
               existing_type=app.models.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('transactions', 'approved_by',
               existing_type=app.models.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('breeding_events', 'created_by',
               existing_type=sa.CHAR(length=36),
               nullable=False)
    op.alter_column('breeding_events', 'event_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('breeding_events', 'technician')
    op.drop_column('breeding_events', 'semen_batch_id')
    op.drop_column('breeding_events', 'sire_id')
    op.alter_column('animals', 'species',
               existing_type=sa.Enum('COW', 'GOAT', 'SHEEP', 'AVIAN', 'CAPRINE', 'OVINE', 'BOVINE', 'PORCINE', 'FELINE', 'CANINE', 'LEPRINE', 'OTHERS', name='animalspecies', native_enum=False),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.drop_index(op.f('ix_staff_queries_id'), table_name='staff_queries')
    op.drop_table('staff_queries')
    op.drop_index(op.f('ix_staff_id'), table_name='staff')
    op.drop_table('staff')
    # ### end Alembic commands ###
