"""add_deworming_status

Revision ID: 68787272dd92
Revises: fff24971f091
Create Date: 2026-07-02 00:19:08.489313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68787272dd92'
down_revision: Union[str, Sequence[str], None] = 'fff24971f091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('deworming_status', sa.String(length=255), nullable=True))
    
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        import app
        op.alter_column('animals', 'species',
                   existing_type=sa.VARCHAR(length=5),
                   type_=sa.Enum('COW', 'GOAT', 'SHEEP', 'AVIAN', 'CAPRINE', 'OVINE', 'BOVINE', 'PORCINE', 'FELINE', 'CANINE', 'LEPRINE', 'OTHERS', name='animalspecies', native_enum=False),
                   existing_nullable=False)
        op.alter_column('transactions', 'approved_by',
                   existing_type=sa.VARCHAR(length=36),
                   type_=app.models.base.GUID(),
                   existing_nullable=True)
        op.alter_column('transactions', 'reversal_of',
                   existing_type=sa.VARCHAR(length=36),
                   type_=app.models.base.GUID(),
                   existing_nullable=True)
        op.create_foreign_key(None, 'transactions', 'users', ['approved_by'], ['id'])
        op.alter_column('users', 'role',
                   existing_type=sa.VARCHAR(length=7),
                   type_=sa.Enum('OWNER', 'VET', 'MANAGER', 'WORKER', 'PHARMACIST', name='userrole', native_enum=False),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        import app
        op.alter_column('users', 'role',
                   existing_type=sa.Enum('OWNER', 'VET', 'MANAGER', 'WORKER', 'PHARMACIST', name='userrole', native_enum=False),
                   type_=sa.VARCHAR(length=7),
                   existing_nullable=False)
        op.drop_constraint(None, 'transactions', type_='foreignkey')
        op.alter_column('transactions', 'reversal_of',
                   existing_type=app.models.base.GUID(),
                   type_=sa.VARCHAR(length=36),
                   existing_nullable=True)
        op.alter_column('transactions', 'approved_by',
                   existing_type=app.models.base.GUID(),
                   type_=sa.VARCHAR(length=36),
                   existing_nullable=True)
        op.alter_column('animals', 'species',
                   existing_type=sa.Enum('COW', 'GOAT', 'SHEEP', 'AVIAN', 'CAPRINE', 'OVINE', 'BOVINE', 'PORCINE', 'FELINE', 'CANINE', 'LEPRINE', 'OTHERS', name='animalspecies', native_enum=False),
                   type_=sa.VARCHAR(length=5),
                   existing_nullable=False)
    op.drop_column('animals', 'deworming_status')
    # ### end Alembic commands ###
