"""Add breeding_events table and pedigree columns to animals

Revision ID: 6d39b1942be1
Revises: 82605882581d
Create Date: 2026-06-27 07:46:49.807754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = '6d39b1942be1'
down_revision: Union[str, Sequence[str], None] = '82605882581d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeding_events',
    sa.Column('animal_id', app.models.base.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_by', app.models.base.GUID(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breeding_events_animal_id'), 'breeding_events', ['animal_id'], unique=False)
    op.create_index(op.f('ix_breeding_events_event_date'), 'breeding_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_breeding_events_event_type'), 'breeding_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_breeding_events_id'), 'breeding_events', ['id'], unique=False)
    
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sire_id', app.models.base.GUID(), nullable=True))
        batch_op.add_column(sa.Column('dam_id', app.models.base.GUID(), nullable=True))
        batch_op.add_column(sa.Column('genetic_line', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('genetic_line')
        batch_op.drop_column('dam_id')
        batch_op.drop_column('sire_id')
        
    op.drop_index(op.f('ix_breeding_events_id'), table_name='breeding_events')
    op.drop_index(op.f('ix_breeding_events_event_type'), table_name='breeding_events')
    op.drop_index(op.f('ix_breeding_events_event_date'), table_name='breeding_events')
    op.drop_index(op.f('ix_breeding_events_animal_id'), table_name='breeding_events')
    op.drop_table('breeding_events')
    # ### end Alembic commands ###
