"""Add milk_records and lactations tables

Revision ID: 82605882581d
Revises: beba59960b7b
Create Date: 2026-06-27 07:40:35.156494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = '82605882581d'
down_revision: Union[str, Sequence[str], None] = 'beba59960b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lactations',
    sa.Column('animal_id', app.models.base.GUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('lactation_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lactations_animal_id'), 'lactations', ['animal_id'], unique=False)
    op.create_index(op.f('ix_lactations_id'), 'lactations', ['id'], unique=False)
    op.create_table('milk_records',
    sa.Column('animal_id', app.models.base.GUID(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('milking_session', sa.String(length=20), nullable=False),
    sa.Column('quantity_liters', sa.Float(), nullable=False),
    sa.Column('fat_percentage', sa.Float(), nullable=True),
    sa.Column('protein_percentage', sa.Float(), nullable=True),
    sa.Column('is_withdrawn', sa.Boolean(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milk_records_animal_id'), 'milk_records', ['animal_id'], unique=False)
    op.create_index(op.f('ix_milk_records_id'), 'milk_records', ['id'], unique=False)
    op.create_index(op.f('ix_milk_records_record_date'), 'milk_records', ['record_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milk_records_record_date'), table_name='milk_records')
    op.drop_index(op.f('ix_milk_records_id'), table_name='milk_records')
    op.drop_index(op.f('ix_milk_records_animal_id'), table_name='milk_records')
    op.drop_table('milk_records')
    op.drop_index(op.f('ix_lactations_id'), table_name='lactations')
    op.drop_index(op.f('ix_lactations_animal_id'), table_name='lactations')
    op.drop_table('lactations')
    # ### end Alembic commands ###
