"""Add poultry and hatchery tables

Revision ID: 8a2cc0e71525
Revises: 6d39b1942be1
Create Date: 2026-06-27 07:53:27.355325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = '8a2cc0e71525'
down_revision: Union[str, Sequence[str], None] = '6d39b1942be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hatchery_batches',
    sa.Column('egg_source', sa.String(length=100), nullable=False),
    sa.Column('egg_count', sa.Integer(), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('set_date', sa.Date(), nullable=False),
    sa.Column('expected_hatch_date', sa.Date(), nullable=False),
    sa.Column('fertile_eggs', sa.Integer(), nullable=True),
    sa.Column('hatched_chicks', sa.Integer(), nullable=True),
    sa.Column('failed_eggs', sa.Integer(), nullable=True),
    sa.Column('initial_egg_cost', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hatchery_batches_id'), 'hatchery_batches', ['id'], unique=False)
    op.create_table('poultry_batches',
    sa.Column('batch_type', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('initial_count', sa.Integer(), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.Column('initial_chick_cost', sa.Float(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poultry_batches_id'), 'poultry_batches', ['id'], unique=False)
    op.create_table('hatchery_events',
    sa.Column('batch_id', app.models.base.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('created_by', app.models.base.GUID(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['hatchery_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hatchery_events_batch_id'), 'hatchery_events', ['batch_id'], unique=False)
    op.create_index(op.f('ix_hatchery_events_event_date'), 'hatchery_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_hatchery_events_event_type'), 'hatchery_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_hatchery_events_id'), 'hatchery_events', ['id'], unique=False)
    op.create_table('poultry_events',
    sa.Column('batch_id', app.models.base.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('created_by', app.models.base.GUID(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['poultry_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poultry_events_batch_id'), 'poultry_events', ['batch_id'], unique=False)
    op.create_index(op.f('ix_poultry_events_event_date'), 'poultry_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_poultry_events_event_type'), 'poultry_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_poultry_events_id'), 'poultry_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poultry_events_id'), table_name='poultry_events')
    op.drop_index(op.f('ix_poultry_events_event_type'), table_name='poultry_events')
    op.drop_index(op.f('ix_poultry_events_event_date'), table_name='poultry_events')
    op.drop_index(op.f('ix_poultry_events_batch_id'), table_name='poultry_events')
    op.drop_table('poultry_events')
    op.drop_index(op.f('ix_hatchery_events_id'), table_name='hatchery_events')
    op.drop_index(op.f('ix_hatchery_events_event_type'), table_name='hatchery_events')
    op.drop_index(op.f('ix_hatchery_events_event_date'), table_name='hatchery_events')
    op.drop_index(op.f('ix_hatchery_events_batch_id'), table_name='hatchery_events')
    op.drop_table('hatchery_events')
    op.drop_index(op.f('ix_poultry_batches_id'), table_name='poultry_batches')
    op.drop_table('poultry_batches')
    op.drop_index(op.f('ix_hatchery_batches_id'), table_name='hatchery_batches')
    op.drop_table('hatchery_batches')
    # ### end Alembic commands ###
