"""Add animals and animal_events tables

Revision ID: beba59960b7b
Revises: 18a5ac29d879
Create Date: 2026-06-27 07:30:49.836071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = 'beba59960b7b'
down_revision: Union[str, Sequence[str], None] = '18a5ac29d879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('tag_id', sa.String(length=50), nullable=False),
    sa.Column('species', sa.Enum('COW', 'GOAT', 'SHEEP', name='animalspecies', native_enum=False), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('date_of_acquisition', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD', 'DEAD', 'QUARANTINED', name='animalstatus', native_enum=False), nullable=False),
    sa.Column('current_location_id', sa.String(length=50), nullable=True),
    sa.Column('current_reproductive_status', sa.Enum('OPEN', 'PREGNANT', 'LACTATING', 'DRY', name='reproductivestatus', native_enum=False), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_id'), 'animals', ['id'], unique=False)
    op.create_index(op.f('ix_animals_tag_id'), 'animals', ['tag_id'], unique=True)
    op.create_table('animal_events',
    sa.Column('animal_id', app.models.base.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_category', sa.Enum('IDENTITY', 'HEALTH', 'REPRODUCTION', 'PRODUCTION', 'MANAGEMENT', name='eventcategory', native_enum=False), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_events_animal_id'), 'animal_events', ['animal_id'], unique=False)
    op.create_index(op.f('ix_animal_events_event_category'), 'animal_events', ['event_category'], unique=False)
    op.create_index(op.f('ix_animal_events_event_timestamp'), 'animal_events', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_animal_events_event_type'), 'animal_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_animal_events_id'), 'animal_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animal_events_id'), table_name='animal_events')
    op.drop_index(op.f('ix_animal_events_event_type'), table_name='animal_events')
    op.drop_index(op.f('ix_animal_events_event_timestamp'), table_name='animal_events')
    op.drop_index(op.f('ix_animal_events_event_category'), table_name='animal_events')
    op.drop_index(op.f('ix_animal_events_animal_id'), table_name='animal_events')
    op.drop_table('animal_events')
    op.drop_index(op.f('ix_animals_tag_id'), table_name='animals')
    op.drop_index(op.f('ix_animals_id'), table_name='animals')
    op.drop_table('animals')
    # ### end Alembic commands ###
