"""add_composite_indexes_and_audit_columns

Revision ID: c393e84d636c
Revises: af93c36e9b46
Create Date: 2026-06-27 17:27:00.834091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c393e84d636c'
down_revision: Union[str, Sequence[str], None] = 'af93c36e9b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create composite indexes on event/record tables
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_entity_id'), 'alerts', ['entity_id'], unique=False)
    op.create_index('ix_alerts_entity_lookup', 'alerts', ['entity_type', 'entity_id', 'alert_type', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_entity_type'), 'alerts', ['entity_type'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index('ix_animal_events_composite', 'animal_events', ['animal_id', 'event_type', 'event_timestamp'], unique=False)
    op.create_index('ix_breeding_events_composite', 'breeding_events', ['animal_id', 'event_type', 'event_date'], unique=False)
    op.create_index('ix_milk_records_composite', 'milk_records', ['animal_id', 'record_date'], unique=False)
    
    # Add audit trail columns to transactions (SQLite-compatible with server_default)
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.add_column(sa.Column('is_reconciled', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('approved_by', sa.String(36), nullable=True))
        batch_op.add_column(sa.Column('reversal_of', sa.String(36), nullable=True))
    
    op.create_index('ix_transactions_entity_date', 'transactions', ['related_entity_type', 'related_entity_id', 'transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index('ix_transactions_entity_date', table_name='transactions')
    op.drop_column('transactions', 'reversal_of')
    op.drop_column('transactions', 'approved_by')
    op.drop_column('transactions', 'is_reconciled')
    op.drop_index('ix_milk_records_composite', table_name='milk_records')
    op.drop_index('ix_breeding_events_composite', table_name='breeding_events')
    op.drop_index('ix_animal_events_composite', table_name='animal_events')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_entity_type'), table_name='alerts')
    op.drop_index('ix_alerts_entity_lookup', table_name='alerts')
    op.drop_index(op.f('ix_alerts_entity_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    # ### end Alembic commands ###
