"""add_comprehensive_animal_fields

Revision ID: fff24971f091
Revises: e55f7432b9f1
Create Date: 2026-06-29 16:38:38.177794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = 'fff24971f091'
down_revision: Union[str, Sequence[str], None] = 'e55f7432b9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('image_path', sa.String(length=255), nullable=True))
    op.add_column('animals', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('animals', sa.Column('color', sa.String(length=100), nullable=True))
    op.add_column('animals', sa.Column('unique_marks', sa.String(length=255), nullable=True))
    op.add_column('animals', sa.Column('pedigree_type', sa.String(length=50), nullable=True))
    op.add_column('animals', sa.Column('purpose', sa.String(length=50), nullable=True))
    op.add_column('animals', sa.Column('vaccination_status', sa.String(length=255), nullable=True))
    op.alter_column('transactions', 'approved_by',
               existing_type=sa.VARCHAR(length=36),
               type_=app.models.base.GUID(),
               existing_nullable=True,
               postgresql_using="approved_by::uuid")
    op.alter_column('transactions', 'reversal_of',
               existing_type=sa.VARCHAR(length=36),
               type_=app.models.base.GUID(),
               existing_nullable=True,
               postgresql_using="reversal_of::uuid")
    op.create_foreign_key(None, 'transactions', 'users', ['approved_by'], ['id'])
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('OWNER', 'VET', 'MANAGER', 'WORKER', 'PHARMACIST', name='userrole', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('OWNER', 'VET', 'MANAGER', 'WORKER', 'PHARMACIST', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.alter_column('transactions', 'reversal_of',
               existing_type=app.models.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('transactions', 'approved_by',
               existing_type=app.models.base.GUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.drop_column('animals', 'vaccination_status')
    op.drop_column('animals', 'purpose')
    op.drop_column('animals', 'pedigree_type')
    op.drop_column('animals', 'unique_marks')
    op.drop_column('animals', 'color')
    op.drop_column('animals', 'weight')
    op.drop_column('animals', 'image_path')
    # ### end Alembic commands ###
